### ISSUE TITLE
Download of converted files fails with large files

### ISSUE THREAD

**Issue by bmorerob** [cloudconvert/cloudconvert-php#37] opened 2017-03-22 10:24 UTC
The API works fine with smaller files but when I try to upload a 200Mb+ mp4 the process fails.
The file appears locally but only partially downloaded (file size 0 bytes) and the process goes to a 500 error with the message 

`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 221789177 bytes) in phar:///Sites/website/cloudconvert-php.phar/vendor/guzzlehttp/psr7/src/Stream.php on line 94`

I have tried updating my local php.ini to increase the max_filesize and other limits, but the error still occurs.

**Comment by josiasmontag** [comment] 2017-03-22 10:42
This limit is caused by the `memory_limit` php setting.

In general we do not suggest to use the input method `upload` for huge files. Such and similar problems might occur. Please consider to offer a public (signed) URL to CloudConvert and use the input method `download`.

**Comment by bmorerob** [comment] 2017-03-22 10:46
The `memory_limit` is set to 256M. I will look at the public URL version, is that part of the API?

**Comment by josiasmontag** [comment] 2017-03-22 10:49
[It is](https://cloudconvert.com/api/conversions#start).
```php
$api->convert([
        ...
        'input' => 'download',
        'file' => 'https://public.url.to/input.file'
    ])
```

**Comment by bmorerob** [comment] 2017-03-22 10:59
Almost there!
No memory limit error, but now I get this error message generated by the API:

`Something with your request is wrong: Download failed: HTTP error 404`

The code I'm using is:

```
$api->convert([
    'inputformat' => $filetype,
    'outputformat' => $output,
    'input' => 'download',
    'file' => 'http://mysitehere.com/upload/file.mp4'
])
    ->wait()
    ->downloadAll('./'.$dest.'/');
```

Is that right?

**Comment by josiasmontag** [comment] 2017-03-22 11:01
This error means that your provided URL (`file`parameter) is invalid and your server returns error 404.

**Comment by bmorerob** [comment] 2017-03-22 11:03
Could it be because I'm using my localhost as the address?

**Comment by josiasmontag** [comment] 2017-03-22 11:06
The URL needs to be public

**Comment by bmorerob** [comment] 2017-03-22 11:25
I've switched over to the public URL version as suggested and tried uploading a smaller file from a preview server. The process works, but the large mp4 still fails (back to a white screen of death).

**Comment by josiasmontag** [comment] 2017-03-22 11:35
You might use the [callback method](https://github.com/cloudconvert/cloudconvert-php#using-with-callback) to avoid timeouts. I am closing this here because this is not an issue of the PHP wrapper. For further support contact support@cloudconvert.com.

**Closed by josiasmontag** 2017-03-22 11:35 UTC
